# Generated by Django 6.0.2 on 2026-02-18 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chickapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="register",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("FullName", models.CharField(max_length=20)),
                ("Email_address", models.EmailField(max_length=50)),
                ("Password", models.CharField(max_length=20)),
                ("Confirm_password", models.CharField(max_length=20)),
            ],
        ),
    ]
