# Generated by Django 6.0.2 on 2026-02-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chickapp", "0002_register"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="message",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="order",
            name="message",
            field=models.TextField(blank=True, default=""),
        ),
    ]
