# Generated by Django 6.0.2 on 2026-02-18 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chickapp', '0004_product_order_amount_order_order_code_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('mpesa', 'M-Pesa'), ('airtel_money', 'Airtel Money'), ('cash', 'Cash on Delivery')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_phone',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_reference',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
