# Generated by Django 6.0.2 on 2026-02-20 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chickapp', '0006_order_mpesa_checkout_request_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='surname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='register',
            name='Confirm_password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='register',
            name='Email_address',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='register',
            name='FullName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='register',
            name='Password',
            field=models.CharField(max_length=255),
        ),
    ]
